# Shell variables
# Generated by 'wal'
wallpaper='/home/admin/Pictures/wallpapers/1707584312691245.jpg'

# Special
background='#332015'
foreground='#ebdac2'
cursor='#ebdac2'

# Colors
color0='#332015'
color1='#AC8C5D'
color2='#D4A15C'
color3='#7D989E'
color4='#A1A9A3'
color5='#D8BA93'
color6='#BDC1AD'
color7='#ebdac2'
color8='#a49887'
color9='#AC8C5D'
color10='#D4A15C'
color11='#7D989E'
color12='#A1A9A3'
color13='#D8BA93'
color14='#BDC1AD'
color15='#ebdac2'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
